version: "3.8"

services:
  flow2api-headed:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.headed
    image: flow2api:headed
    ports:
      - "38000:8000"
    volumes:
      - flow2api_data:/app/data
      - flow2api_tmp:/app/tmp
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOW_DOCKER_HEADED_CAPTCHA=true
      - DISPLAY=:99
      - XVFB_SCREEN=1440x900x24
    shm_size: "2gb"
    restart: unless-stopped
